### ISSUE TITLE
Disable logger

### ISSUE THREAD

**Issue by Wyne10** [xvik/yaml-updater#143]
Hello, 

i couldn't find if it is possible to disable logger from YamlUpdater. I'm using java library v1.4.4. Any help with that?

Thanks.

**Comment by xvik** [comment]
Helllo! The library use slf4j for logging so you can simply set WARN or ERROR level for `ru.vyarus.yaml` (in you logging configuration) to hide messages.

Honestly, I'm not sure why it is a problem for you. Maybe I misunderstand your problem. If my answer isn't helpful enough please describe your problem with more details and I'll try to help.

**Comment by Wyne10** [comment]
Sorry, i'm not familiar with slf4j. I've added slf4j-simple to classpath

`implementation 'org.slf4j:slf4j-simple:1.7.36'`

And then included simplelogger.properties to src/main/resources

`org.slf4j.simpleLogger.defaultLogLevel=OFF
org.slf4j.simpleLogger.log.ru.vyarus=OFF`

But it doesn't seem to have any effect. I've also tried to do the same for test classpath.

**Comment by xvik** [comment]
Your simplelogger configuration should disable logs entirely (and it seems correct). By the way, there should be no logs at all if you remove slf4j-simple jar (only a warning, which can be removed with [slf4j-nop](https://www.slf4j.org/codes.html#noProviders)).

Maybe you have logback or log4j which are used instead of simplelogger.

Can you please show me an example of messages you are tring to get rid of.  Mayve it would provide some hints.

**Comment by Wyne10** [comment]
I'm trying to get rid of:

`[17:22:07 INFO]: [ru.vyarus.yaml.updater.YamlUpdater] New configuration parsed (269 bytes, 18 lines)
[17:22:07 INFO]: [ru.vyarus.yaml.updater.YamlUpdater] Current configuration parsed (309 bytes, 19 lines)
[17:22:07 INFO]: [ru.vyarus.yaml.updater.YamlUpdater] Configuration merged
[17:22:07 INFO]: [ru.vyarus.yaml.updater.YamlUpdater] Merged file correctness validated
[17:22:07 INFO]: [ru.vyarus.yaml.updater.YamlUpdater] Configuration not changed`

Unfortunately, slf4j-nop didn't work either. The thing is, i'm using your library in the [Paper](https://github.com/PaperMC/Paper) plugin. I guess it somehow interferes with slf4j, so i can't change configuration. Anyway, i appreciate your help, there is probably nothing i can do about it.

**Comment by xvik** [comment]
As I can see, Paper use log4j 2 for logging, and so not simplelogger or noplogger would work.
But you can change log level [at runtime](https://logging.apache.org/log4j/2.12.x/faq.html#reconfig_level_from_code) (before calling updater):

```java
Configurator.setLevel("ru.vyarus", Level.WARN);
```
(Configurator is a [log4j class](https://logging.apache.org/log4j/2.x/javadoc/log4j-core/org/apache/logging/log4j/core/config/Configurator.html))

**Comment by Wyne10** [comment]
Thank you so much, it worked, but it needs to be like this:
```java
Configurator.setLevel(LogManager.getLogger("ru.vyarus"), Level.WARN);
````
