### ISSUE TITLE
RFE: Docker Container?

### ISSUE THREAD

**Issue by TJM** [xvik/yaml-updater#46]
I would like it if you would add the Dockerfile, and host the image here on github (GHCR). We have it hosted internally at the moment, but as we were trying to run our renovate pipelines in an external gitlab-runner, they failed to reach the internally hosted instance. If you are interested, I could PR the file and the github actions to build/publish it.

Here is the Dockerfile we are using (which likely needs updated), this would actually maybe even be easier if you are already building the app, you could create the container by just "COPY" (ing) the artifact over instead of downloading it :)

```dockerfile
FROM frolvlad/alpine-glibc:alpine-3.15

ARG VERSION=1.4.1

RUN wget -O /usr/local/bin/yaml-updater https://github.com/xvik/yaml-updater/releases/download/${VERSION}/yaml-updater-linux-amd64 \
  && chmod +x /usr/local/bin/yaml-updater

CMD ["/usr/local/bin/yaml-updater", "--help"]
```

**Comment by xvik** [comment]
It would be great if you can do a PR. Also would appreciate help with github action. 
I'm busy with other things now, but if it would be fast to release after your PR I'll of course do it.
