### ISSUE TITLE
GraalVM version of the CLI ?

### ISSUE THREAD

**Issue by aadrian** [xvik/yaml-updater#7]
Hi,

Any chance creating a GraalVM version of the CLI tool?
https://picocli.info/picocli-on-graalvm.html 

As just one simple executable it could be simpler to deploy it in more environments where a JDK might not be present, and also have it on the path as a general tool.

Thank you.

**Comment by xvik** [comment]
Hi!

Yes, definitely. I'm thinking about it since the beginning, but have no time yet to do it.

**Comment by xvik** [comment]
Native binaries now attached to release https://github.com/xvik/yaml-updater/releases/tag/1.4.0
